# Generated by Django 4.2.3 on 2023-08-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_room_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Presidencial', 'Presidencial')], default='Single', max_length=50),
        ),
    ]
