# Generated by Django 4.2.3 on 2023-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_capacity',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1, max_length=10),
        ),
    ]
