# Generated by Django 4.2.3 on 2023-08-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_room_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.CharField(choices=[('ocupada', 'ocupada'), ('libre', 'libre'), ('en limpieza', 'en limpieza'), ('mantenimiento', 'mantenimiento')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_capacity',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Doble', 'Doble'), ('Suite', 'Suite'), ('Presidencial', 'Presidencial')], default='Single', max_length=50),
        ),
    ]
