# Generated by Django 4.2.4 on 2023-08-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0009_remove_room_room_capacity_room_room_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
