# Generated by Django 4.2.4 on 2023-08-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_reservation_days_reservation_price_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='days',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price_total',
        ),
    ]
